import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime

def generate_report(event_dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.darkblue,
        spaceAfter=30
    )
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.maroon,
        spaceAfter=10
    )
    normal_style = styles['Normal']

    # Format Satellite Acquisition Time
    raw_timestamp = event_dict.get('timestamp', '')
    if raw_timestamp:
        try:
            dt = datetime.fromisoformat(str(raw_timestamp).replace('Z', '+00:00'))
            acq_time_str = dt.strftime('%Y-%m-%d %H:%M:%S UTC')
        except Exception:
            acq_time_str = str(raw_timestamp)
    else:
        acq_time_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')

    # 1. Header
    elements.append(Paragraph(f"INCIDENT REPORT: {event_dict.get('id')}", title_style))
    elements.append(Paragraph(f"Satellite Acquisition Time: {acq_time_str} | CONFIDENTIAL", normal_style))
    elements.append(Spacer(1, 20))

    # 2. Executive Summary
    elements.append(Paragraph("Executive Summary", header_style))
    summary_text = f"An event classified as {event_dict.get('classification')} with severity {event_dict.get('severity')} " \
                   f"was detected at location ({event_dict.get('lat')}, {event_dict.get('lon')}) at acquisition time {acq_time_str}."
    elements.append(Paragraph(summary_text, normal_style))
    elements.append(Spacer(1, 15))

    # 3. Thermal Intelligence
    elements.append(Paragraph("Thermal Intelligence", header_style))
    data = [
        ['Metric', 'Value'],
        ['Acquisition Time', acq_time_str],
        ['Fire Radiative Power (MW)', str(event_dict.get('frp'))],
        ['Brightness', str(event_dict.get('brightness'))],
        ['Cluster Size', str(event_dict.get('cluster_size'))],
        ['Est. Duration (hrs)', str(event_dict.get('duration_hours'))]
    ]
    t = Table(data, colWidths=[200, 200])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 15))

    # 4. Industrial Context
    elements.append(Paragraph("Industrial Context", header_style))
    elements.append(Paragraph(f"Nearest Facility: {event_dict.get('nearest_facility_name')} ({event_dict.get('nearest_facility_type')})", normal_style))
    elements.append(Paragraph(f"Distance: {event_dict.get('nearest_facility_dist_km')} km", normal_style))
    elements.append(Spacer(1, 15))
    
    # 7. Environmental Impact
    elements.append(Paragraph("Environmental Impact", header_style))
    elements.append(Paragraph(f"Est. CO2 Emissions: {event_dict.get('co2_estimate')} tonnes", normal_style))
    elements.append(Paragraph(f"Likely Chemicals: {event_dict.get('likely_chemicals')}", normal_style))
    elements.append(Paragraph(f"Affected Area: {event_dict.get('affected_area_km2')} sq km", normal_style))
    elements.append(Spacer(1, 30))

    # 11. Footer
    elements.append(Paragraph("Generated by AI Industrial Fire Monitor", normal_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
